# Generated by Django 5.1.6 on 2025-03-14 07:57

import django.db.models.deletion
import django.utils.timezone
import file_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文件标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='文件描述')),
                ('file', models.FileField(upload_to=file_manager.models.get_file_path, verbose_name='文件')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件类型')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_manager.filecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-upload_date'],
            },
        ),
    ]
